# .readthedocs.yml

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

formats:
  - htmlzip
  - epub
