# Pipy upload strax after a release (or manually).
# Mostly based on https://github.com/marketplace/actions/pypi-publish
name: Pipy

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup steps
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install build
      - name: Build package
        run: python -m build
      # Do the publish
      - name: Publish a Python distribution to PyPI
        # Might want to add but does not work on workflow_dispatch :
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pipy_token }}
          password: ${{ secrets.pypi_password }}
