# Test if we can actually install strax by installing
name: Installation test

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
    branches:
      - master
      - stable
  push:
    branches:
      - master

jobs:
  build:
    name: "py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install strax
        run: pip install .
      - name: Test import
        run: python -c "import strax; print(strax.__version__)"
      - name: goodbye
        run: echo goodbye
